### ISSUE TITLE
Do these images support mkbundle?

### ISSUE THREAD

**Issue by Costigan** [mono/docker#35]
Hello.  mkbundle exists in these images as /usr/bin/mkbundle, but I can't find find cc or gcc.  Aren't they required for mkbundle?

I realize that I can build an image on top of these that contains one or the other compiler, so the question is this: is mkbundle supported out-of-the-box, or are we intended to build an image on top of these if we want to use it? (Which would be fine.)
 Thanks,
     Mark Shirley

**Comment by akoeplinger** [comment]
GCC isn't installed by default, so yes for mkbundle you need to install it yourself.

Note that there's also work in progress for mkbundle that removes this need (by allowing you to download a prebuilt Mono runtime instead of going the embedding route mkbundle does right now) which will ship in a future version of Mono.

I'm closing this, but feel free to ask follow up questions :)

**Comment by Costigan** [comment]
That’s a fine answer.  Thank you. - Mark
