### ISSUE TITLE
Interest in Dockerfile for Apache mod_mono?

### ISSUE THREAD

**Issue by MariusVolkhart** [mono/docker#51]
I recently needed to set up a docker container running Apache w/ `mod_mono`. I was disappointed to find that there wasn't a base image available for this, as the setup wasn't entirely straightforward.

I've since created an image based on `debian/stretch` with minimal additional software, making the image as close to production-ready as I can easy get it.

Are you interested in this `dockerfile` and in supporting a `mod_mono` image going forward?

**Comment by akoeplinger** [comment]
Could you please paste the Dockerfile you used so I get an idea for what it does?

I'll talk to a few people what they think about a `mod_mono` image 😄

**Comment by akoeplinger** [comment]
We've since created a `slim` variant of the image which contains only the `mono-runtime` and dependent Debian packages. This should make basing an image which contains mod_mono in top of the mono:slim image much easier and slimmer ;)

Given there wasn't a lot of interest/response in this issue I think it's better to keep a mod_mono image outside of this repo for now, but please feel free to post any links to Dockerfile here. Thanks!
